FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# Solo reqs del frontend (liviano)
COPY requirements.frontend.txt .
RUN python -m pip install --upgrade pip && \
    pip install -r requirements.frontend.txt

# Código frontend
COPY frontend ./frontend

EXPOSE 7860
CMD python frontend/app.py
